export { newGame } from "./newGame"
export type { NewGameAccounts } from "./newGame"
export { newEg } from "./newEg"
export type { NewEgAccounts } from "./newEg"
export { newPlayer } from "./newPlayer"
export type { NewPlayerArgs, NewPlayerAccounts } from "./newPlayer"
export { newFlag } from "./newFlag"
export type { NewFlagAccounts } from "./newFlag"
export { newMegaPiece } from "./newMegaPiece"
export type { NewMegaPieceArgs, NewMegaPieceAccounts } from "./newMegaPiece"
export { newPiece } from "./newPiece"
export type { NewPieceArgs, NewPieceAccounts } from "./newPiece"
export { movePiece } from "./movePiece"
export type { MovePieceArgs, MovePieceAccounts } from "./movePiece"
export { moveMegaPiece } from "./moveMegaPiece"
export type { MoveMegaPieceArgs, MoveMegaPieceAccounts } from "./moveMegaPiece"
